# Generated by Django 3.0.3 on 2023-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
